POST http://127.0.0.1:8000/create_user HTTP/1.1
content-type: application/json


{

    "username" : "Lyrics254",
    "email_address" : "thomasambetsa@gmail.com",
    "password" : "Lyricssi",
    "about" : "gasfdghsvabfdshbvhdf",
    "profile_picture" : "http://127.0.0.1:8000/ak.png"
    
    
}
